### ISSUE TITLE
Create the add client form

### ISSUE THREAD

**Issue by Karyum** [webahead14/clinic-admin#4]
For this task you will need to create a form where a new client will be added, the user would need to input the following data:
1) full name (text input)
2) government id (text input)
3) email (text input)
4) passcode (password input)
5) phone number (text input)
6) condition (text input)
7) gender (radio buttons)
8) start date (date input)
9) protocol (select input)
10) Reminders (3 time inputs)

**all this data must be saved to a react state**
> Don't create a state for each input, just 1 state which is an object that holds all the data.

at the bottom you will also need an `Add client` button which on click it will send the data to the API to add the client at `https://wa14-clinic-api.herokuapp.com/api/client/register` a `POST` request which data looks like this:

```javascript
{
    name: "",
    passcode: "",
    govId: "",
    condition: "",
    phone: "",
    email: "",
    gender: 1,
    protocolId: "",
    startDate: "",
    reminders: ['12:00', '08:30', '15:10'],
}

```

### you don't to need check if the request was successful or not, just make sure you are sending the data to that url and the data looks like the object above ⬆️

Here are links on how to build the form using ant design

- [Form](https://ant.design/components/form/)
- [Text Input](https://ant.design/components/input/)
- [Radio input](https://ant.design/components/radio/)
- [Select input](https://ant.design/components/select/)
- [Date input](https://ant.design/components/date-picker/)

![add-client-admin](https://user-images.githubusercontent.com/24195641/152525194-0f4be0ac-2842-4b1e-b1b4-0b1631de66dc.PNG)

**Comment by MuhannadYazbak** [comment]
I can't find the URL of the page in order to test my progress

**Comment by Karyum** [comment]
it's `/add/client` you can find all the routes in the `App.jsx` file [written here](https://github.com/webahead14/clinic-admin/blob/main/src/App.jsx#L109-L119)

**Comment by MuhannadYazbak** [comment]
Thanks

**Comment by Karyum** [comment]
@MuhannadYazbak this is done ?

**Comment by Karyum** [comment]
Ah I just saw you merged your own pull request 😅
